language: rust
before_script:
  - rustup component add rustfmt-preview
  - cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
script:
  - cargo build --verbose
  - cargo fmt -- --write-mode=diff
  - cargo clippy -- -D clippy
  - cargo test --verbose

