language: rust
rust:
  - nightly
before_script:
  - rustup component add rustfmt-preview
  - cargo install clippy || echo "clippy is already installed"
script:
  - cargo build --verbose
  - cargo fmt -- --check
  - cargo clippy
  - cargo test --verbose

