[package]
name = "cvmaker"
version = "0.1.0"
authors = ["Miloslav Žežulka <zezulka95@gmail.com>"]

[dependencies]
cursive = "0.8.2"
chrono = "0.4.4"
fast_chemail = "0.9.5"
phonenumber = "0.2.1+8.9.0"
url = "1.7.1"
iso_country = "0.1.2"
isolang = "0.2.1"
derive_builder = "0.5.1"
linked_hash_set = "0.1.3"
mongodb = "0.3.9"
vfs = "0.2.0"